project-tsurugi/tsubakuro

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/FutureIpcWireImpl.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/StreamConnectorImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/406

add mutual exclusiion of close() and get() in FutureIpcWireImpl

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/408

Cleaner should be static

---

modules/debug/build.gradle
modules/debug/src/example/java/com/tsurugidb/tsubakuro/debug/example/DebugClientExample.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/DebugClient.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/DebugServiceCode.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/DebugServiceException.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/LogLevel.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/Constants.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/DebugClientImpl.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/DebugService.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/DebugServiceStub.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/package-info.java
modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/package-info.java
modules/debug/src/main/proto/tateyama/proto/debug/request.proto
modules/debug/src/main/proto/tateyama/proto/debug/response.proto
modules/debug/src/test/java/com/tsurugidb/tsubakuro/debug/impl/DebugClientImplTest.java
settings.gradle

tsurugidbに外部から任意のログを追加する方法を提供する #435
のクライアントを作成しました。

Debugclient

---

modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/impl/DebugServiceStub.java

https://github.com/project-tsurugi/tsurugi-issues/issues/416

use newRequest() in DebugServiceStub

---

modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/ServerWireImpl.java

Fixed occasional stream wire test failures

revise ServerWireImpl for test

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/client/ServiceClientCollector.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/client/ServiceClientCollectorTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/480

enable obtain SMV code

---

modules/ipc/src/main/native/include/wire.h
modules/ipc/src/main/native/src/connectionJNI.cpp
modules/ipc/src/main/native/src/wireJNI.cpp
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ResultSetWireTest.java
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/181

implement server alive check in ResultSetWireImpl.getChunkNative()

---

modules/proto/src/main/protos/jogasaki/proto/sql/request.proto

https://github.com/project-tsurugi/tsurugi-issues/issues/496 のためにprotoファイル定義のdump optionを拡張します。

sql proto fileをjogasakiと同期(arrowサポートのためにdump optionを拡張)

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/StreamConnectorImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/592

revise streamLink connection flow

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/601

fix stream socket leak at handshake error

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/601

apply commnets

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/Wire.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/SessionWireTest.java

https://github.com/project-tsurugi/tsurugi-issues/discussions/607

refactoring of StreamWire related parts

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/611

Release120

---

modules/kvs/src/main/java/com/tsurugidb/tsubakuro/kvs/KvsServiceCode.java

KvsServiceCodeについて、``@Doc``アノテーションを追加しました。
ついでに、Javadocのコメントも若干修正しました。

docs: add annotation to kvs diagnostic code enums.

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlServiceCode.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlServiceException.java

https://github.com/project-tsurugi/tsurugi-issues/issues/646#issuecomment-1947658247

revise doc for SqlServiceException

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/datastore/DatastoreServiceCode.java

This PR revises diagnostic code list to help guide to upgrade guide.

docs: revise diagnostics for guidance to upgrade guide.

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java
modules/proto/src/main/protos/tateyama/proto/diagnostics.proto

https://github.com/project-tsurugi/tsurugi-issues/issues/75

add OPERATION_CANCELED to tateyama/proto/diagnostics.proto

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/FutureIpcWireImpl.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/connection/ConnectionTest.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/AbstractFutureResponse.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/common/SessionBuilderTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/AbstractFutureResponse.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/ServerWireImpl.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/SessionWireTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/617

allowed Future[Ipc|Stream]WireImpl.get() to be called more than once

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/756

revise synchronized usage in IpcConnectorImpl

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/common/Session.java

apply https://nautilus-rd.slack.com/archives/GB4QT920L/p1715307461698729?thread_ts=1715304777.095029&cid=GB4QT920L

fix twisted default processing in Session

---

modules/ipc/src/main/native/include/wire.h

https://github.com/project-tsurugi/tsurugi-issues/issues/75

make session smoke test pass

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ResultSetWireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java

https://github.com/project-tsurugi/tsurugi-issues/issues/640

make session smoke test pass (Session.close)

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/IpcLink.java
modules/ipc/src/main/native/include/com_tsurugidb_tsubakuro_channel_ipc_IpcLink.h
modules/ipc/src/main/native/include/wire.h
modules/ipc/src/main/native/src/wireJNI.cpp
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/issues/640

make session smoke test pass (Session.shutdown)

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java

https://github.com/project-tsurugi/tsurugi-issues/issues/799

avoid NPE and print status information

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetBox.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetWireImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/567

revise messages when the connection with the database is lost

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/issues/640

invoke Link.close() when Session.shutdown() finishes successfully

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/IpcLink.java
modules/ipc/src/main/native/include/wire.h
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/SessionWireTest.java

https://github.com/project-tsurugi/tsurugi-issues/discussions/809

get rid of 'server crash' from any error message

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java

https://github.com/project-tsurugi/tsurugi-issues/issues/37

update service_message_version_minor for new ExplainByText message

---

modules/proto/src/main/protos/tateyama/proto/core/request.proto
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/Session.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/ServiceShelf.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/379

revert accidentally reverted files

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/issues/880

make StreamLink not send REQUEST_SESSION_BYE

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/914

spare response slot for update expiration_ ime

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/914

sendUpdateExpirationTime() can now be executed concurrently

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/922

Release 1.6.0 snapshot

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java

This PR fixes link in @Doc annotation to generate error-code-tsurugi-services.md

Fix reference link in @Doc

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/963

Release 1.7.0 snapshot

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java

https://github.com/project-tsurugi/tsurugi-issues/issues/948

revise cancel and SCD-00403 diagnostics message handling

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponseTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/955#issuecomment-2339564749

refactor ChannelResponse

---

modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponseTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/955#issuecomment-2342993432

put back ChannelResponseTest and adapt it to ServerException handling

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/util/FutureResponse.java

https://github.com/project-tsurugi/tsurugi-issues/issues/111

make strict specification of FutureResponse.close()

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Queues.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java

https://github.com/project-tsurugi/tsurugi-issues/issues/111#issuecomment-2440931402

fixed and refactored handling of cancellations for queued requests

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/111#issuecomment-2445773271

fix Session.shutdown() to work correctly

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/1024

Origin/release 1.8.0 snapshot

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/PreparedStatementImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SessionImplTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImplTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1022#issuecomment-2484563545
「トランザクションのクローズに対するケアが抜けていたという話なので、本Issueでそちらも対応してください。」

make Transaction and PreparedStatement close() execute asynchronously

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/PreparedStatementImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SessionImplTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImplTest.java

return to commit 87b3aba1d87bbbb4f76d38b1fef7d503735e9500
Merge: b32aa367 78a20365
Author: Takashi Horikawa <horikawa@nautilus-technologies.com>
Date:   Tue Nov 12 15:25:40 2024 +0900
Merge pull request #497 from project-tsurugi/origin/release_1.8.0-SNAPSHOT
Origin/release 1.8.0 snapshot

return to 87b3aba1d87bbbb4f76d38b1fef7d503735e9500

---

modules/ipc/src/main/native/include/wire.h

https://github.com/project-tsurugi/tsurugi-issues/issues/1105

eliminates redundant conditional judgments when performing wakeup by EOR

---

modules/ipc/src/main/native/include/wire.h

https://github.com/project-tsurugi/tsurugi-issues/issues/1105

revert unnecessary change

---

modules/proto/src/main/protos/jogasaki/proto/sql/common.proto
modules/proto/src/main/protos/jogasaki/proto/sql/request.proto
modules/proto/src/main/protos/jogasaki/proto/sql/response.proto
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1114
https://github.com/project-tsurugi/jogasaki/pull/134#issuecomment-2597592631

update sql proto. files to be the same as jogasaki

---

modules/proto/src/main/protos/tateyama/proto/framework/common.proto
modules/proto/src/main/protos/tateyama/proto/framework/request.proto
modules/proto/src/main/protos/tateyama/proto/framework/response.proto

update framework proto. files to be the same as tateyama

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/BlobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ClobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ValueInputBackedRelationCursor.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueInput.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/ValueInput.java

accommodate the latest specifications of serde at blob and clob

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlService.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java

revise sql.openReader(ref)

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java

address corner cases in blob/clob processing

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ResultSetImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java

reviewed communications regarding blob/clob

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/BlobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ClobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientTest.java

revise exceptions thrown in dealing with large objects

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/LargeObjectCache.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1113#issuecomment-2617758485

add LargeObjectCache and related APIs

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/LargeObjectCache.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlService.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/LargeObjectCacheImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1113#issuecomment-2653865441

API for copying a large object moved to SqlClient

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/discussions/1130

make StreamLink receive in the fowrawd method

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponseLobTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobTest.java

add tests for ChannelResponse to receive Lob

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponseLobTest.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockLink.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/IpcLink.java
modules/ipc/src/main/native/include/com_tsurugidb_tsubakuro_channel_ipc_IpcLink.h
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/StreamConnectorImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetBox.java

iceaxe-testingからのアクセスに必要な部分はpublicを残す。
本PRが組み込まれた後にiceaxe-testingに対するPRを用意し、それが反映されたらpublicを消去する。

change ResponseBox class to not public

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/BlobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ClobReferenceForSql.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueInput.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueOutput.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/ValueInput.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/ValueOutput.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueInputTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueOutputTest.java
modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/impl/testing/Entry.java
modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/impl/testing/EntrySequenceValueInput.java
modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/impl/testing/EntrySequenceValueOutput.java

add tests for blob/clob serde

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1147

revise blob error handling

---

modules/ipc/src/main/native/include/wire.h

https://github.com/project-tsurugi/tsurugi-issues/issues/1156

try to avoid race in receiving ResultSet

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java
modules/proto/src/main/protos/jogasaki/proto/sql/common.proto
modules/proto/src/main/protos/tateyama/proto/diagnostics.proto

https://github.com/project-tsurugi/tsurugi-issues/issues/1149#issuecomment-2712325667

Prepare for 13

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1142

BlobException is passed through

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1147#issuecomment-2716812139

revise BLOB error message

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1142#issuecomment-2717198046

revise BLOB error message (2nd)

---

modules/ipc/src/main/native/include/udf_wires.h
modules/ipc/src/main/native/include/wire.h

https://github.com/project-tsurugi/tsurugi-issues/issues/1156

improve robustness of ResultSet handling in IPC

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/1166

Release 1.9.0 snapshot

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/sql/ResultSetWire.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ResultSetWireImpl.java
modules/ipc/src/main/native/include/com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl.h
modules/ipc/src/main/native/include/udf_wires.h
modules/ipc/src/main/native/include/wire.h
modules/ipc/src/main/native/src/wireJNI.cpp
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/ResultSet.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ResultSetImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ValueInputBackedRelationCursor.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/io/StreamBackedValueInput.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/util/LoadBuilder.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/PathTest.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetWireImpl.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/ServerStreamLink.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetWireTest.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/ServerWireImpl.java

implement timeout for ResultSet.nextRow()

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1179

delete one line that were left as FIXME

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Queues.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ResponseBox.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockLink.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/IpcLink.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1170

enhance slot usage check

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ResultSetImpl.java

throws ResponseTimeoutException when ResultSetImpl.nextRow() times out

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ValueInputBackedRelationCursor.java

fix delivery path for timeout

---

modules/ipc/src/main/native/src/wireJNI.cpp

fix overflow in timeout value calculation

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/sql/ResultSetWire.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ResultSetWireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/sql/ResultSetWireImpl.java

eliminate redundant timeout value calculation

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/common/BlobPathMapping.java
modules/debug/src/test/java/com/tsurugidb/tsubakuro/debug/impl/DebugServiceStubTest.java
modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/KvsClientImplTest.java
modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/KvsServiceStubTest.java
modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/TransactionHandlImplTest.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/common/impl/SessionImplTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobWithMappingTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1151

BlobPathMapping

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1170

add a check if the socket is closed or not when receiving TCP/IP channel

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobWithMappingTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1151

taking into account differences in path delimiters

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/TableMetadata.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TableMetadataAdapter.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TableMetadataAdapterTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1189

add TableMetadata.getDescription()

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobWithMappingTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1151

use Path.startWith() insted of String.startWith()

---

modules/proto/src/main/protos/jogasaki/proto/sql/request.proto
modules/proto/src/main/protos/jogasaki/proto/sql/response.proto

https://github.com/project-tsurugi/tsurugi-issues/issues/346

update sql/[request|response].proto to be the same as jogasaki

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1151

converted blob file paths are also checked for exists and readability

---

modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java

https://github.com/project-tsurugi/tsurugi-cb/actions/runs/14605846631/job/40974591137#step:8:1296

flush the outStream outputting to the socket before closing it

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SessionImplTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1022

add SessionImpl.waitForCompletion()

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1022

fix timeout handling at Transaction.close()

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlService.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/util/SqlRequestUtils.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java
modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/impl/RequestHandler.java
modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/util/SqlResponseUtils.java

https://github.com/project-tsurugi/tsurugi-issues/issues/346

implement GetTransactionStatus and its tests

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1062#issuecomment-2843784875

alter TransactionImpl.autoDispose to false

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1022

fix a decision on the condition to terminate the Disposer thread

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/TransactionStatus.java

https://github.com/project-tsurugi/tsurugi-issues/issues/346

add @since to TransactionStatus

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1023

fix to not stall after improperly closing Session

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1023#issuecomment-2881988809

do not throw the same exception twice

---

buildSrc/src/main/groovy/tsubakuro.java-base.gradle

https://github.com/project-tsurugi/tsurugi-issues/issues/1220

Release 1.10.0 snapshot

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java

fix for https://github.com/project-tsurugi/tsubakuro/commit/85857d770374005cc5ef2fcafb2a007d565c4aee

do futureResponses.close() prior to resources.close() in SqlServiceStub

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java
modules/ipc/src/main/native/include/com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl.h

https://github.com/project-tsurugi/tsurugi-issues/issues/1232

set upper limet of timeout for IpcConnectorImpl.IpcConnectorImpl()

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1227

add Transaction.commit() that uses SqlRequest.CommitOption

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1227

keep Transacion.commit(SqlRequest.CommitStatus) API alive

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1022#issuecomment-2929360503

apply comments

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/TableMetadata.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TableMetadataAdapter.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TableMetadataAdapterTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1140

implement TableMetadata.getPrimaryKeys

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlService.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/util/SqlRequestUtils.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImplTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1210

implement TransactionImpl.executeDump(String source, Path directory)

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/494#issuecomment-2990001894

remove possible race that may occur when requesting shutdown

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Link.java
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/SessionWireTest.java
modules/stream/src/test/java/com/tsurugidb/tsubakuro/channel/stream/sql/SessionWireTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/494

handle TimeoutException in Link.pullMessage()

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/Crypto.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/FutureIpcWireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/Session.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/util/LoadBuilder.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/util/LoadBuilderTest.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1227#issuecomment-2978628100

add doc comment on Transaction.commit(SqlRequest.CommitOption)

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1238

revise TransactionImpl.close()

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1238

eliminate race in state transision in TransactionImpl

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/PreparedStatementImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1269

fix timeout to make it behave as specified

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/UsernamePasswordCredential.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/425#issuecomment-3177374746

allow empty password

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/425

fix behavior when connecting to servers with authentication disabled

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/425

revert UpdateCredentialTask

---

docs/auth-http-ja.md
docs/auth-mock-ja.md
modules/auth-http/README.md
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/Wire.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImplTest.java
modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
modules/proto/src/main/protos/tateyama/proto/endpoint/response.proto
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/Session.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/425#issuecomment-3218727755

Credential2authentication

---

modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/AbstractResultSetProcessor.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ResultSetImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/1298

make AbstractResultSetProcessor.test() idempotent

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImplTest.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockLink.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockResultSetWire.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/ResponseMessage.java
modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/ResponseProtoForTests.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/PreparedStatementImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/AsyncCloseTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/ResultSetTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubLobWithMappingTest.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java

Enhance test

---

modules/common/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockLink.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/AsyncCloseTest.java

enhance AsyncCloseTest to handle no response cases

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/HandshakeTest.java
modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/FutureIpcWireImpl.java
modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/SessionWireTest.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/StreamLink.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/FutureStreamWireImpl.java
modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/StreamConnectorImpl.java

https://github.com/project-tsurugi/tsurugi-issues/issues/425#issuecomment-3256918412

handle timeout on handshake

---

modules/ipc/src/main/native/include/wire.h
modules/ipc/src/main/native/src/wireJNI.cpp

https://github.com/project-tsurugi/tsurugi-issues/issues/1077

use watch_interval in ResultSetWireImpl_getChunkNative()

---

modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Disposer.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/common/impl/SessionImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/PreparedStatementImpl.java
modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SessionImplTest.java

addressed the following error.
```
DbTransactionFutureTest > doNothing_FORCEFUL() > repetition 1 of 6 FAILED
java.lang.AssertionError: Session already closed
```

simplify Disposer process

---

modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/IpcLink.java

Fixed an issue where shutdown would not complete

ensure resultset-wire close when ipcLink is closed
