project-tsurugi/tsubakuro

- modules/proto/src/main/protos/jogasaki/proto/sql/response.proto
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlService.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ExecuteResultAdapter.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlClientImpl.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStub.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImpl.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/util/Load.java
- modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SqlServiceStubTest.java
- modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/TransactionImplTest.java
- modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/util/LoadBuilderTest.java
https://github.com/project-tsurugi/tsurugi-issues/issues/393
The return type of Transaction.executeStatement(), Transaction.executeLoad(), and SqlClient.executeLoad() have changed from Void to ExecuteResult.
> breaking change in API of Transaction.executeStatement(), Transaction.executeLoad(), and SqlClient.executeLoad()

- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/BackgroundFutureResponse.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/Response.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/datastore/DatastoreService.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
Javadocで、警告が出ていた箇所を直しました。
APIのコメントが絡むので、ご確認をよろしくお願いいたします。
・BackgroundFutureResponse.java、ForegroundFutureResponse.java
　存在しない引数の解説を消しました。
・wire/Response.java
　存在しないメソッドへの参照を消しました。問題ないでしょうか。
・datastore/DatastoreService.java
　例外クラス名を直しました。
　以下の記述から、ServerExceptionにしましたが、問題ないでしょうか。
　https://github.com/project-tsurugi/tsubakuro/blob/master/modules/common/src/main/java/com/tsurugidb/tsubakuro/util/FutureResponse.java#L38
・sql/Transaction.java
　存在しないメソッドを、それに近い executeLoad() に直しました。問題ないでしょうか。
・sql/Transaction.java
　``{@code null`` に右カッコをつけました。
> Fix javadoc param etc

- modules/debug/src/main/java/com/tsurugidb/tsubakuro/debug/DebugServiceException.java
- modules/kvs/src/main/java/com/tsurugidb/tsubakuro/kvs/KvsServiceCode.java
- modules/kvs/src/main/java/com/tsurugidb/tsubakuro/kvs/KvsServiceException.java
- modules/kvs/src/main/java/com/tsurugidb/tsubakuro/kvs/Values.java
- modules/kvs/src/main/java/com/tsurugidb/tsubakuro/kvs/impl/KvsService.java
sharksfinからコピペしたコメントに、doxygen独自のタグを利用しているものがありました。通常のビルドではこれが警告やエラーにならず、見逃していました。
javadocにすると、その部分の記述内容が空欄になっていました。
それらをjavadoc形式に直し、正しく記述が表示されることを確認しました。
また、java15以降では、Serializableなクラスについては、privateなフィールドについてもコメントを書かなければならなくなったようです。
現在java11を利用していますが、ついでなので、コメントを追加しておきました。
> fix javadoc (causes warn/errors when publish or using java17)

- modules/auth-mock/src/main/java/com/tsurugidb/tsubakuro/auth/mock/MockTicketProvider.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/FileCredential.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/FutureResponse.java
- modules/explain/src/main/java/com/tsurugidb/tsubakuro/explain/json/JsonPlanGraphLoader.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/datastore/Backup.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/datastore/BackupDetail.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/ResultSet.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Types.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/sql/impl/testing/Relation.java
通常のビルドでは問題にならないものの
・``./gradlew clean publishMavenJavaPublicationToMavenLocal -PmavenLocal ``するとエラーや警告が出る（手元では再現できず）
・java17を使う設定にして ``./gradlew javadoc``するとエラーや警告が出る
javadocコメントが多数ありました。
このうち、エラーとなっている箇所について、すべて修正しました。
残っているのは「コメントが書かれていない」警告だけで、modules/sessionに24箇所です。
protoの自動生成ソースに対する警告は、別途設定で対処する予定です。
なお、javadoc生成エラーの原因は主に以下でした。
・``<p>...<ul>...</ul></p>``の書き方は厳密にはだめらしく、``<p>...</p><ul>...</ul>``に直しました。
・通常の解説コメント中に``List<V>`` などと書くと、``V``というタグがないと言われるので、``{@code List<V>}``などに直しました。
・同じくコード例などで、``<pre> List<V> = func(...); </pre>``などと書くとエラーになるので、``<pre>{@code List<V> ... }</pre>``に直しました。
なお、``{@code ``のあとに改行してからコード例を書き出すと、できたHTMLに余計な空行が入ってしまったため、``<pre>{@code `` 直後に（改行せず）コード例1行目を置きました。
また、``<V>``が使われていないコード例についても、``{@code }``くくりを念の為追加しておきました。
・``@see``のあとに``{@link …
> fix javadoc errors (all warnings of missing comment still remain)

- buildSrc/src/main/groovy/tsubakuro.java-conventions.gradle
- modules/auth-http/build.gradle
- modules/auth-mock/build.gradle
- modules/common/build.gradle
- modules/connector/build.gradle
- modules/debug/build.gradle
- modules/explain/build.gradle
- modules/ipc/build.gradle
- modules/kvs/build.gradle
- modules/proto/build.gradle
- modules/session/build.gradle
- modules/stream/build.gradle
各モジュールのbuild.gradleの設定を修正しました。
大原則として、共通設定を tsubakuro/buildSrc/.../tsubakuro.java-conventions.gradleに置き、各モジュールのbuild.gradleでの設定はすべて削除しました。
そのうえで、以下も行いました。
・checkstyleでprotobufの自動生成ソースを除外
・spotbugsでprotobufの自動生成ソースを除外＆HTML出力追加
・javadocでprotobufの自動生成ソースを除外、常に厳密チェックあり(publish作業時と同等）
・protobufに関わるモジュールをすべて最新バージョンに統一
・modules/session/build.gradleの-Xlint設定をオプションに変更（デフォルトはOFF）
・Gradle 9.0では削除予定の古い書き方を新しい書き方に変更
・その他、空行など、スタイル統一
> Revise build.gradle 231124

- modules/debug/build.gradle
- modules/debug/src/test/java/com/tsurugidb/tsubakuro/debug/impl/DebugServiceStubTest.java
- modules/kvs/build.gradle
- modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/KvsClientImplTest.java
- modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/KvsServiceStubTest.java
- modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/StubUtils.java
- modules/kvs/src/test/java/com/tsurugidb/tsubakuro/kvs/impl/TransactionHandlImplTest.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/ErroneousWire.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockError.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/MockWire.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/RequestHandler.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/SimpleResponse.java
- modules/session/src/testFixtures/java/com/tsurugidb/tsubakuro/mock/package-info.java
・sandbox-tsubakuro-coreにある、MockWireやそれに関係するクラスを tsubakuro/modules/session/src/testFixtures 配下に移植しました。
・tsubakuro/modules/{debug, kvs}のテストに、MockWireを利用したテストを移植・追加しました。特に、commit/rollbackが呼ばれていなければ自動的にrollbackすること、commitはAutoDipose=trueで要求するのでトランザクションハンドルの後始末で disposeTransaction要求が飛ばないこと（それ以外は飛ぶ）などを単体テストで確認できるようになりました。
> Add mock for tests

- modules/proto/src/main/protos/jogasaki/proto/sql/request.proto
- modules/proto/src/main/protos/jogasaki/proto/sql/response.proto
https://github.com/project-tsurugi/tsurugi-issues/issues/496 でparquet/arrowの詳細ファイルフォーマットをサポートするための変更です。
> sync sql proto files with jogasaki (adding arrow support)

- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/SqlClient.java
https://github.com/project-tsurugi/tsurugi-issues/issues/496 で行ったprotobuf msg変更( https://github.com/project-tsurugi/tsubakuro/pull/393 https://github.com/project-tsurugi/tsubakuro/pull/395 ) のため、sqlクライアントのSMV minor versionを更新します。
> feat: update sql SMV minor version to support dump file formats

- buildSrc/src/main/groovy/tsubakuro.java-library-conventions.gradle
This PR suppress the following warnings that execute gradlew with `publish` ot related task.
```
Maven publication 'mavenJava' pom metadata warnings (silence with 'suppressPomMetadataWarningsFor(variant)'):
- Variant testFixturesApiElements:
- Declares capability com.tsurugidb.tsubakuro:tsubakuro-session-test-fixtures:1.3.0-SNAPSHOT which cannot be mapped to Maven
- Variant testFixturesRuntimeElements:
- Declares capability com.tsurugidb.tsubakuro:tsubakuro-session-test-fixtures:1.3.0-SNAPSHOT which cannot be mapped to Maven
These issues indicate information that is lost in the published 'pom' metadata file, which may be an issue if the published library is consumed by an old Gradle version or Apache Maven.
The 'module' metadata file, which is used by Gradle 6+ is not affected.
```
We …
> build: Suppress warnings for publishing testFixtures

- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/Doc.java
This PR introduces `@Doc` annotation for document generation.
This is mainly designed for generates document about a list of structured error codes.
> docs: add annotation for document generation.

- modules/common/src/main/java/com/tsurugidb/tsubakuro/client/ServiceClientCollector.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/DiagnosticCodeCollector.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/BasicDocumentSnippet.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/ClassCollector.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/Doc.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/DocumentSnippet.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/util/DocumentedElement.java
- modules/common/src/main/resources/META-INF/tsurugidb/diagnostic-code
- modules/common/src/test/java/com/tsurugidb/tsubakuro/exception/DiagnosticCodeCollectorTest.java
- modules/common/src/test/java/com/tsurugidb/tsubakuro/exception/MockDiagnosticCode.java
- modules/common/src/test/java/com/tsurugidb/tsubakuro/util/BasicDocumentSnippetTest.java
- modules/common/src/test/java/com/tsurugidb/tsubakuro/util/DocumentedElementTest.java
This PR introduces a framework to collect document snippets of the diagnostic codes.
see the below:
* modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/DiagnosticCodeCollector.java
* collects diagnostic code classes, and extracts their documents.
* modules/common/src/test/java/com/tsurugidb/tsubakuro/exception/DiagnosticCodeCollectorTest.java
* shows how use `DiagnosticCodeCollector`
* modules/common/src/main/resources/META-INF/tsurugidb/diagnostic-code
* adds diagnostic code enum class to definition file
* modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceCode.java
* adds `@Doc` annotation
> docs: add feature to collect docs of diagnostic code.

- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/impl/ExecuteResultAdapter.java
This PR will improve resillience against unknown enum field of `CounterType` from SQL service.
Please consider put debug logs when unknown fields were found.
> fix: ignore unknown counter types of `ExecuteResult`.

- modules/ipc/src/main/native/include/udf_wires.h
Ubuntu 24.04 の Beta 版で tsubakuro のビルドが失敗します。
udf_wires.h では `std::set` を使用していますが `#include <set>` が不足しています。
同時に使用している boost ライブラリが、Ubuntu 22.04 で使用している boost のバージョン (1.74.0) では、その内部から `<set>` を include していたため、udf_wires.h のほうで不足していても今までビルドが通っていたものが、新しい 1.83.0 では `<set>` を include しなくなったため通らなくなったようです。
対応として、明示的に `#include <set>` を追加しました。
```
In file included from /home/ban/build/src/tsurugidb-1.0.0-BETA4-gcc11/tsubakuro/modules/ipc/src/main/native/src/wireJNI.cpp:20:
/home/ban/build/src/tsurugidb-1.0.0-BETA4-gcc11/tsubakuro/modules/ipc/src/main/native/include/udf_wires.h:211:10: error: 'set' in namespace 'std' does not name a template type
211 |     std::set<resultset_wires_container*> resultset_wires_set_{};
|          ^~~
In file included from …
```
> add missing include (for FTBFS with boost-1.83.0)

- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
- modules/session/src/test/java/com/tsurugidb/tsubakuro/sql/impl/SessionImplTest.java
Cancel request will not be made for the time being due to insufficient processing of "cancel".
> revert cancel() invocation from ForegroundFutureResponse.close()

- buildSrc/build.gradle
- buildSrc/src/main/groovy/tsubakuro.java-conventions.gradle
- buildSrc/src/main/resources/source-header.txt
This Pull Request introduce [License Gradle Plugin](https://github.com/hierynomus/license-gradle-plugin) for maintaining source header.
> build: introduce license-gradle-plugin

- modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponse.java
- modules/common/src/main/java/com/tsurugidb/tsubakuro/exception/CoreServiceException.java
- modules/common/src/test/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/ChannelResponseTest.java
fix: rethrow CoreServiceException
BREAKING CHANGE: In ChannelResponse, IOException was thrown, but changed to CoreServiceException.
> fix: rethrow CoreServiceException

- modules/ipc/src/main/native/CMakeLists.txt
tsubakuro は AWT を必要としていないため、本来は AWT の含まれない JDK 環境 (`*-jdk-headless` パッケージ) だけあればビルド出来るべきですが、現状そうなっておらず jawt.h がないことを理由に CMake が通らずビルドできません。
この問題への対応として、 CMake が JDK の AWT を探しに行かないように変更します。
案件: project-tsurugi/tsurugi-issues#1064
> build: prevent CMake from finding jawt.h; for headless jdk

- .github/workflows/ci-publish.yml
As ubuntu 24.04 is currently still experimental support
See: https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes
> ci: modify runs-on for preventing ubuntu-latest

- modules/session/src/main/java/com/tsurugidb/tsubakuro/sql/Transaction.java
This pull request includes a minor documentation update to the `Transaction.java` file. The change adds a note indicating that the `executeQuery(String, Path)` is not yet implemented.
> Add javadoc about executeDump(String, Path) is not yet implemented

- modules/ipc/src/main/native/CMakeLists.txt
This pull request includes a small change to the `modules/ipc/src/main/native/CMakeLists.txt` file. A message was added to display the value of `JNI_LIBRARIES` during the build process.
> build: show resolved jni libraries for building Tsubakuro Native

- buildSrc/src/main/groovy/tsubakuro.java-base.gradle
This pull request adds a new Gradle task to the `java-base` build script for displaying the Java toolchain's installation path.
Build script enhancement:
* [`buildSrc/src/main/groovy/tsubakuro.java-base.gradle`](diffhunk://#diff-aacf013a0d3af8beecbbe1fb58b09e1ec6b7829305f9e2224a6bbf2a4be615b9R14-R21): Introduced a new task `showToolchainJavaHome` that prints the `installationPath` of the configured Java toolchain. This can be useful to build JNI library in tsubakuro-ipc
> build: add showToolchainJavaHome Gradle task
